runLimits:
  throttleField: "Acceleration pedal position (%)"
  minThrottleValue: 95
  minCount: 20
fields:
  - "Time (ISO)"
  - "Engine speed (rpm)"
  - "Air flow rate (gm/s)"
  - "Ignition timing advance (Cyl. 1) (°)"
  - "Calculated load value (%)"
  - "Vehicle speed (km/h)"
  - "Intake manifold absolute pressure (kPa)"
  - "Intake manifold relative pressure (bar)"
  - "Barometric pressure (kPa)"
  - "Fuel cut"
  - "Intake air temperature (°C)"
  - "Wastegate valve (%)"
  - "O2 Sensor (Bank 1, Sensor 1) (V)"
  - "O2 Sensor (Bank 1, Sensor 2) (V)"
  - "Fuel injection pulse width (Cyl. 1, Bank 1) (ms)"
  - "Engine oil temperature (°C)"
  - "Short term fuel trim (Bank 1) (%)"
  - "Fuel rail pressure (kPa)"
  - "Long term fuel trim (Bank 1) (%)"
  - "Total term fuel trim (Bank 1) (%)"
  - "A/F feedback control 1"
  - "Acceleration pedal position (%)"
  - "Throttle position sensor (%)"
  - "Target throttle position (%)"
  - "Fuel injector time (min/hour)"
  # - "Fuel injector time (min/100 km)"
  - "Target fuel rail pressure (kPa)"
  # - "Target idle speed (rpm)"
  # - "Engine coolant temperature (°C)"
  # - "Barometric pressure (mmHg)"
  # - "EVAP Canister purge value (%)"
  - "VVT (In, Bank 1) diff (target-actual) (°)"
  # - "ISC/IAC control throttle (%)"
  # - "Main throttle sensor (V)"
  # - "Assistant throttle sensor (V)"
  # - "Main accelerator sensor (V)"
  # - "Assistant accelerator sensor (V)"
  # - "Battery voltage (V)"
  # - "Fuel tank level (%)"
  # - "Refrigerant pressure (kPa)"
  # - "Generator field monitor duty (%)"
  # - "Battery current (A)"
  # - "Battery temperature (°C)"
  # - "Generator regulator voltage (com) (V)"
  # - "Radiator fan"
  # - "Radiator fan (2-speed)"
  # - "A/C fan"
  # - "A/C compressor clutch"
  # - "Fuel pump"
  # - "Intake manifold tuning valve actuator"
  # - "Throttle motor relay signal"
  # - "Intake manifold runner control (IMRC) valve"
  # - "Starter switch"
  # - "PS signal"
  # - "A/C switch"
  # - "Blower fan load signal"
  # - "Brake boost pressure state"
  # - "Break switch"
  # - "Electric load"
  # - "D range signal (inverse?)"
  # - "Cruise Resume/Acceleration switch"
  # - "Cruise Set/Coast switch"
  # - "Cruise cancel switch"
  # - "Cruise on/off switch"
  # - "Idle (CTP) switch"
  # - "O2 Sensor activity (Bank 1, Sensor 1)"
  # - "O2 Sensor activity (Bank 1, Sensor 2)"
